routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | Admin Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register Admin routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['namespace' => 'Auth', 'as' => 'admin.'], function () {
    Route::get('/admin', function () {
        return redirect('admin/login');
    });
    Route::get('/login', 'AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminLoginController@login')->name('login.submit');
    Route::post('/logout', 'AdminLoginController@logout')->name('logout');

    //admin password reset routes
    Route::post('/password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'AdminResetPasswordController@reset')->name('password.reset.post');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');

});

Route::group(['middleware' => 'isAdmin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');
    
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\AdminResetPasswordNotification;
use Illuminate\Database\Eloquent\SoftDeletes;

class Admin extends Authenticatable {
    
    use Notifiable;
    use SoftDeletes;

    protected $guard = 'admin';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'admin_uuid', 'admin_id', 'firstname', 'lastname', 'email', 'password', 'status', 'type', 'last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * Check if current user has an avatar
     *
     * @return string|false
     */
    public function getAvatarPathAttribute() {
        return public_path('images/avatars/' . md5($this->id . $this->created_at) . '.jpg');
    }

    /**
     * Return current user avatar uri
     *
     * @return string
     */
    public function getAvatarUrlAttribute() {
        if (is_file($this->avatar_path)) {
            $ts = filemtime($this->avatar_path);
            return asset('images/avatars/' . md5($this->id . $this->created_at) . '.jpg?t=' . $ts);
        }
        return asset("/images/default_user.png");
    }

    public function sendPasswordResetNotification($token) {
        $this->notify(new AdminResetPasswordNotification($token));
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

class HomeController extends Controller
{
    public function index() {
        return view('admin.dashboard');
    }

}

app/Http/Controllers/Api/V1/User/UserController.php
<?php

namespace App\Http\Controllers\Api\V1\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Services\Api\V1\User\UserService;

class UserController extends Controller
{
    private $user_service;

    /**
     * User Service Construct
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
    */
    public function __construct(UserService $user_service) {

          $this->user_service= $user_service;
    }

    /**
     * User Login
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
    */
    public function login(Request $request) {
        return $this->user_service->login($request);
    }

    /**
     * User Register
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
    */
    public function register(Request $request)
    {
        return $this->user_service->register($request);
    }
}

app/Http/Controllers/ApiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ApiController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void`
     */
    public function __construct() {
        $this->middleware(['webApi']);
    }

    public function setApiLanguageUserDriver($param, $type) {

        return true;
    }

    public function testLoad(){

      return $this->successResponse('');

    }

    public function successResponse($status, $data = '', $count = 0, $pageLimit = 0) {
        $page = null;
        $page['totalCount'] = $count;
        $page['limit'] = $pageLimit."";
        if (!empty($data)) {
            return response()->json([
                        "statusCode" => 1000,
                        "message" => $status,
                        "data" => $data,
                        "page" => $page,
            ]);
        } else {
            return response()->json([
                        "statusCode" => 1000,
                        "message" => $status
            ]);
        }
    }

    public function errorResponse($status, $errorMessage = null) {
        return response()->json([
                    "statusCode" => 2000,
                    "message" => $status,
                    "errorMessage" => $errorMessage
        ]);
    }

    public function sessionOutResponse($status) {
        return response()->json([
                    "statusCode" => 3000,
                    "message" => $status
        ]);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/includes/chat-box.blade.php
<!-- START CHAT_BOT -->
<div class="ccw_plugin chatbot" style="bottom:10px; left:10px;">
    <div class="ccw_style9 animated no-animation ccw-no-hover-an"> 
        <a target="_blank" href="https://web.whatsapp.com/send?phone=919633432212&amp;text=Feel Free to ask any question! " class="img-icon-a nofocus"> 
            <img class="img-icon ccw-analytics lazyloaded" id="style-9" data-ccw="style-9" style="height: 48px;" src="https://india.portraitflip.com/wp-content/plugins/click-to-chat-for-whatsapp/./assets/img/whatsapp-icon-square.svg" alt="WhatsApp chat" data-lazy-src="https://india.portraitflip.com/wp-content/plugins/click-to-chat-for-whatsapp/./assets/img/whatsapp-icon-square.svg" data-was-processed="true">
            <noscript>
                <img class="img-icon ccw-analytics" id="style-9" data-ccw="style-9" style="height: 48px;" src="https://india.portraitflip.com/wp-content/plugins/click-to-chat-for-whatsapp/./assets/img/whatsapp-icon-square.svg" alt="WhatsApp chat">
            </noscript> 
        </a>
    </div>
</div>
<!-- END CHAT_BOT -->

resources/views/admin/includes/footer.blade.php
<!-- FOOTER -->

<!-- BEGIN FOOTER -->
<div class="success_box"></div>
<div class="alert_box_general"></div>
<div class="warning_box_general"></div>
<div class="page-footer">
    <div class="page-footer-inner"> <?php echo date('Y') ?> &copy; Streamline Systems</div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- BEGIN CORE PLUGINS -->

<script src="{{ asset('global/plugins/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('global/plugins/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>


<script src="{{ asset('global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}"
        type="text/javascript"></script>
<script src="{{ asset('global/scripts/app.js') }}" type="text/javascript"></script>
<script src="{{ asset('layouts/layout/scripts/layout.js') }}" type="text/javascript"></script>


<!-- include summernote css/js -->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
{{--summer note for--}}


<!--DATA TABLES-->
<script src="{{ asset('global/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}"
        type="text/javascript"></script>


{{--Jquery UI library--}}
<script src="{{ asset('js/ui-jquery.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/idle-timer.min.js') }}" type="text/javascript"></script>

<!--SELECT2-->
<script src="{{ asset('global/plugins/select2/js/select2.full.min.js') }}" type="text/javascript"></script>

<!-- DATE / TIME PICKER -->
<script src="{{ asset('global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"
        type="text/javascript"></script>
<script src="{{ asset('global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js') }}"
        type="text/javascript"></script>
<script src="{{ asset('global/plugins/components-date-time-pickers.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"
        type="text/javascript"></script>


{{--Compose email--}}
{{--  @include('general.email.compose')  --}}

{{--@if(TASKS_ACCESS_LEVEL != 5)--}}
{{--Add new task model--}}
{{--  @include('general.tasks.task_add')  --}}
{{--@endif--}}
{{-- Quotes tab --}}
{{--  @include('general.quotes.quote_add')  --}}
{{-- Quotes tab --}}

{{--Role delegation popup--}}
{{--  @include('general.role_delegation_popup')  --}}
{{--Role delegation popup--}}

{{--Global functions and variables--}}

<script src="{{asset('global/scripts/ibm.js') }}" type="text/javascript"></script>

<script src="{{ asset('js/intlTelInput.js') }}" type="text/javascript"></script>
{{--  <script src="{{ asset('js/global_script.js') }}" type="text/javascript"></script>  --}}
{{--  <script src="{{ asset('js/tasks.js') }}" type="text/javascript"></script>  --}}
{{--  <script src="{{ asset('js/notification_center.js') }}" type="text/javascript"></script>  --}}
<script src="{{ asset('js/quote.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/croppie.js') }}"></script>
<script src="{{ asset('js/email.js') }}" type="text/javascript"></script>
<script src="{{asset('js/sweetalert.js') }}" type="text/javascript"></script>
<script src="{{asset('js/formstone_core.js')}}"></script>
<script src="{{asset('js/formstone_file_uploader.js')}}"></script>
{{-- <script src="{{asset('js/multi_upload-v1.0.js?v=1.4.7')}}"></script> --}}
{{--  <script src="{{asset('js/file_uploads.js') }}" type="text/javascript"></script>  --}}

resources/views/admin/includes/head.blade.php
<head>
    <meta charset="utf-8" />
    <title>{{ env('APP_NAME') }} @yield('title')</title>
    <meta id="viewport" name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width" />
    <meta http-equiv="Content-Type" content="text/html"/>
    <!-- <link rel="shortcut icon" type="image/png" href="images/icons/fav.png"/> -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('css/components.min.css') }}" />

    <link rel="stylesheet" type="text/css" href="{{ asset('public/global/layout/css/layout.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('css/darkblue.min.css') }}" />

    <link rel="stylesheet" type="text/css" href="{{ asset('public/global/select2/css/select2.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('public/global/select2/css/select2-bootstrap.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('plugins/global/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('plugins/global/bootstrap-toastr/toastr.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('css/custom-style.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('css/custom.css') }}" />
    
    <style>
        #language-switch {
            margin-right: 30px;
            margin-top: 8px;
            color: #ffffff;
            background-color: #333;
            border: 1px solid #333 !important;
            width: 200px;
            padding: 5px;
            border-radius: 5px;
            outline: none;
        }
    </style>
    
    <!--[if IE]>
    <link href="ie.css" rel="stylesheet" type="text/css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

resources/views/admin/includes/header.blade.php
<!-- BEGIN HEADER INNER -->
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="">
                <img src="{{asset('images/logo.png')}}" alt="logo" class="logo-default"> </a>
            <div class="menu-toggler sidebar-toggler"></div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">

            <ul class="nav navbar-nav pull-right">
                <!---SET LANGUAGE -->
                <!--MENU BUTTON TOGGLE-->
                <li class="dropdown dropdown-user">
                    <span class="menu_bar_toggle">
                        <i class="fa fa-plus"></i>
                    </span>
                </li>
                <!-- <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                    <a href="javascript:;" class="dropdown-toggle" id="notificationscount">
                        <i class="fa fa-bell"></i>
                        <span class="badge badge-default"> 0 </span>
                    </a>
                </li> -->
                <!--MENU BUTTON TOGGLE-->
                <div class="dropdown-menu_custom box" style="">
                    <div class="noti_head">
                        <div class="not_title">Notifications <span class="not_count">0</span></div>
                        <div class="view_all_link"><a href=""><i class="fa fa-arrow-up"></i></a></div>
                    </div>
                    <div class="notifications">
                        <div class="each_notification">No notifications found.</div>
                    </div>
                </div>
                <!-- END NOTIFICATION DROPDOWN -->
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user">
                    <a href="" class="dropdown-toggle user_options" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle" src="images/avatar2.png" />
                        <span class="username username-hide-on-mobile">{{ Auth::guard('admin')->user()->email }}</span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                </li>
                <!-- END USER LOGIN DROPDOWN -->
                <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-quick-sidebar-toggler">
                    <a href="" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                        class="logout" title="Logout">
                        <i class="fa fa-sign-out"></i>
                    </a>
                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
                <!-- END QUICK SIDEBAR TOGGLER -->
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
</div>
<!-- END HEADER INNER -->





<!-- TOP-BAR USER DTS -->
<div class="user_drop_menu box" style="display: none;">
	<span class="each_option_drop delegate_role">Delegate Role</span>
	<a href="" class="each_option_drop switch_user" style="color: #000;">Profile</a>
</div>
<!-- END TOP-BAR USER-PRO -->
<!-- TOP-BAR USER-DTS -->
<div class="nav_bar_menu box" style="display: none;">
	<div class="inner_wrap">
		<span class="title">CONTACTS</span>
		<div class="menu_row">
			<div class="each_menu">
				<a href="">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/lead.png') }}">
					<span>Account</span>
				</a>
			</div>
			<div class="each_menu">
				<a href="">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/customer.png') }}">
					<span>Contact</span>
				</a>
			</div>
			<div class="each_menu">
				<a href="">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/supplier.png') }}">
					<span>Employee</span>
				</a>
			</div>
		</div>
	</div>
	<div class="inner_wrap">
		<span class="title">SALES ACTIVITIES</span>
		<div class="menu_row">
			<div class="each_menu">
				<a href="">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/lead.png') }}">
					<span>Lead</span>
				</a>
			</div>
			<div class="each_menu">
				<a href="">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/customer.png') }}">
					<span>Opportunity</span>
				</a>
			</div>
		</div>
	</div>
	<div class="inner_wrap">
		<span class="title">TASK &amp; ACTIVITIES</span>
		<div class="menu_row">
			<div class="each_menu">
				<a href="" class="global_add_new_task">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/quotation.png') }}">
					<span>Task</span>
				</a>
			</div>
			<div class="each_menu hide">
				<a href="">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/quotation.png') }}">
					<span>Note</span>
				</a>
			</div>
			<div class="each_menu">
				<a href="" class="add_new_quote_general">
					<img class="each_menu_img" src="{{ asset('public/global/img/topbar_icons/quotation.png') }}">
					<span>Quote</span>
				</a>
			</div>
		</div>
	</div>
	
</div>
<!-- END TOP-BAR USER-DTS -->
<!-- TOP-BAR USER DTS -->
<div class="user_drop_premises box" style="display: none;">
	<a href="" class="each_option_drop switch_user">Nostalgia Dubai Mall</a>
	<a href="" class="each_option_drop switch_user">Nostalgia Dubai Mall</a>
	<a href="" class="each_option_drop switch_user">Nostalgia Dubai Mall</a>
	<a href="" class="each_option_drop switch_user">Nostalgia Dubai Mall</a>
</div>
<!-- END TOP-BAR USER-PRO -->

resources/views/admin/includes/msg.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif
@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif
@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

resources/views/admin/includes/sidebar.blade.php
<!-- //CRM SIDEBAR -->
<div class="page-sidebar-wrapper">
	<div class="page-sidebar navbar-collapse collapse">
		<!-- CRM SIDEBAR MENU -->
		<ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-closed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
			<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
			<li class="sidebar-toggler-wrapper hide">
				<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
				<div class="sidebar-toggler"></div>
				<!-- END SIDEBAR TOGGLER BUTTON -->
			</li>

			<!--******************************************** Campaigns ********************************************-->
			<li class="nav-item start {{ Request::is('admin*') ? 'active' : ''}}">
				<a href="{{ route('admin.dashboard') }}" class="nav-link nav-toggle">
					<img src="{{ asset('images/sidebar_icons/campaigns.png') }}" class="sidebar_icons">
					<span class="title">Dashboard</span>
				</a>
			</li>

			<!--******************************************** Content List ********************************************-->
			{{-- <li class="nav-item start parent_li {{ Request::is('admin/content-list*') ? 'active' : ''}}">
				<a href="{{ route('admin.content-list.index') }}" class="nav-link nav-toggle">
					<img src="{{ asset('images/sidebar_icons/content_list.png') }}" class="sidebar_icons">
					<span class="title">Content List</span>
					<span class="arrow"></span>
				</a>
			</li> --}}
			
			<!--******************************************** all_tv ********************************************-->
			{{-- <li class="nav-item start parent_li {{ Request::is('admin/screens*') ? 'active' : ''}}">
				<a href="{{ route('admin.screens.index') }}" class="nav-link nav-toggle">
					<img src="{{ asset('images/sidebar_icons/all_tv.png') }}" class="sidebar_icons">
					<span class="title">Screens</span>
				</a>
			</li> --}}

			<!--******************************************** Venues ********************************************-->
			{{-- <li class="nav-item start parent_li {{ Request::is('admin/venues*') ? 'active' : ''}} ">
				<a href="{{ route('admin.venues.index') }}" class="nav-link nav-toggle">
					<img src="{{ asset('images/sidebar_icons/placeholder.png') }}" class="sidebar_icons">
					<span class="title">Venues</span>
					<span class="arrow"></span>
				</a>
			</li> --}}

			<!--******************************************** User Manager ********************************************-->
			{{-- <li class="nav-item start {{ Request::is('admin/users*') ? 'active' : ''}}">
				<a href="{{ route('admin.users.index') }}" class="nav-link nav-toggle">
					<img src="{{ asset('images/sidebar_icons/user_manager.png') }}" class="sidebar_icons">
					<span class="title">User Manager</span>
				</a>
			</li> --}}

			<!--******************************************** settings ********************************************-->
			{{-- <li class="nav-item start {{ Request::is('admin/settings*') ? 'active' : ''}}">
				<a href="{{ route('admin.settings.index') }}" class="nav-link nav-toggle">
					<img src="{{ asset('images/sidebar_icons/settings.png') }}" class="sidebar_icons">
					<span class="title">Settings</span>
					<span class="arrow"></span>
				</a>
			</li>  --}}

			

		</ul>
		<!-- END SIDEBAR MENU -->
	</div>
</div>
<!-- END CRM SIDEBAR -->